version: "3.8"

services:
  activemq:
    image: apache/activemq-artemis:latest
    container_name: artemis_broker
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker/node2:/var/lib/artemis-instance/etc-override

  crawler:
    image: giselabcr8888/crawler:1.2.0
    container_name: crawler
    ports:
      - "7070:7070"
    environment:
      - ACTIVEMQ_URL=failover:(tcp://10.26.14.221:61616,tcp://10.26.14.222:61616,tcp://10.26.14.223:61616)
    depends_on:
      - activemq
    networks:
      - engine-net
    volumes:
      - engine-volume:/app

  indexer:
    image: giselabcr8888/indexer:1.1.0
    container_name: indexer
    environment:
      - NODE_IP=10.26.14.222
      - JAVA_TOOL_OPTIONS=-XX:-UseContainerSupport
      - MONGO_URL=mongodb://10.26.14.222:27017
      - ACTIVEMQ_USERNAME=clusterUser
      - ACTIVEMQ_PASSWORD=secret123
      - ACTIVEMQ_URL=tcp://10.26.14.222:61616
      - HAZELCAST_MEMBERS=10.26.14.221:5701,10.26.14.222:5701,10.26.14.223:5701
    ports:
      - "8080:8080"
      - "5701:5701"
    depends_on:
      - activemq
    networks:
      - engine-net
    volumes:
      - engine-volume:/app

  search:
    image: giselabcr8888/search:1.2.0
    container_name: search
    environment:
      - NODE_IP=10.26.14.222
      - JAVA_TOOL_OPTIONS=-XX:-UseContainerSupport
      - DATABASE_NAME=books
      - COLLECTION_METADATA=metadata
      - COLLECTION_INDEX=inverted_index
      - MONGO_URL=mongodb://10.26.14.222:27017
      - HAZELCAST_MEMBERS=10.26.14.223:5701,10.26.14.222:5701,10.26.14.221:5701
    ports:
      - "9090:9090"
      - "5702:5701"
    depends_on:
      - activemq
    networks:
      - engine-net
    volumes:
      - engine-volume:/app/data

  syncthing:
    image: linuxserver/syncthing:2.0.12
    container_name: syncthing
    hostname: node2
    #    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Atlantic/Canary
      - STGUIAPIKEY=mysecretapikey
    volumes:
      - ./syncthing_config:/config
      - engine-volume:/app
    ports:
      - "8384:8384"       # Web UI
      - "22000:22000/tcp" # Sync Traffic
      - "22000:22000/udp" # Sync Traffic
      - "21027:21027/udp" # Local Discovery
    restart: unless-stopped

networks:
  engine-net:
    driver: bridge

volumes:
  engine-volume:
