version: "3.8"

services:
  search1:
    image: giselabcr8888/search:multi
    container_name: search1
    expose:
      - "9090"
    networks:
      - search_net

  search2:
    image: giselabcr8888/search:multi
    container_name: search2
    expose:
      - "9091"
    networks:
      - search_net

  search3:
    image: giselabcr8888/search:multi
    container_name: search3
    expose:
      - "9092"
    networks:
      - search_net

  nginx:
    image: nginx:trixie-perl
    container_name: search_nginx
    ports:
      - "8000:8000"   # entrada desde host → nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - search1
      - search2
      - search3
    networks:
      - search_net

networks:
  search_net:
    driver: bridge
