upstream search_backend {
    least_conn;
    server search:9090 max_fails=3 fail_timeout=30s;
}

upstream indexing_backend {
    server indexing:8080 max_fails=3 fail_timeout=30s;
}

upstream ingestion_backend {
    server ingestion:7070 max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name _;

    location /search/ {
        proxy_pass http://search_backend/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location /index/ {
        proxy_pass http://indexing_backend/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location /ingest/ {
        proxy_pass http://ingestion_backend/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location /health {
        return 200 'nginx OK';
        add_header Content-Type text/plain;
    }
}
