{
 "title": "Search Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Query latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum{http_route=\"/search\"}[5m])/rate(http_server_request_duration_seconds_count{http_route=\"/search\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{exported_job=\"search-service\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{exported_job=\"search-service\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"search-service\"} |= ``"
    }
   ]
  }
 ]
}